#!/bin/sh
zathura ./Cohomology\ of\ real\ Grassmannians.pdf &
vim ./Cohomology\ of\ real\ Grassmannians.tex ./chapters/intro.tex ./chapters/grassmannian.tex ./appendices/stiefel.tex ./appendices/CW.tex ./appendices/fiber_bundles.tex
