---
name: Makefile CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install texlive-full
          sudo apt-get install texmaker
          sudo apt-get install texlive-bibtex-extra
          sudo apt-get install biber
      - name: run Makefile
        run: make

      - name: upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: Cohmology_of_real_Grassmannians
          path: "Cohomology of real Grassmannians.pdf"
          retention-days: 20
